[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = [
  "crates/coordinator_zomes/*",
  "crates/integrity_zomes/*",
]


[workspace.dependencies]
hdi = "0.2.0-beta-rc.1"
hdk = "0.1.0-beta-rc.1"
serde = "1"
holochain = "0.1.0-beta-rc.2"
