[package]
edition = "2021"
name = "hc_zome_profiles_coordinator"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_profiles_coordinator"

[dependencies]

hc_zome_profiles_integrity = "0.0.1"
hc_zome_profiles_coordinator = "0.0.1"